services:
  nats:
    image: nats:alpine
    ports:
      - '4222:4222'

  users:
    build:
      context: .
    command:
      - pnpm
      - run
      - start:dev
      - users
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      NATS_SERVERS: nats://nats:4222

  books:
    build:
      context: .
    command:
      - pnpm
      - run
      - start:dev
      - books
    ports:
      - '3001:3000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      NATS_SERVERS: nats://nats:4222

volumes:
  node_modules: