{
 "title": "Library app",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Request / endpoint",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(http_route) (calls_total{http_method=~\"GET\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "service": "nest-app" }
   ]
  },
  {
   "title": "Request duration (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_duration_milliseconds_bucket{http_method=~\"GET|POST\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg by(http_route) (rate(calls_total{http_method=\"GET\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}